/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ascii.h"

int *
convert_1_svc(var *argp, struct svc_req *rqstp)
{
	static int  result;

	result =(int)(argp->chara);

	return &result;
}
