/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASCII_H_RPCGEN
#define _ASCII_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct var {
	char chara;
};
typedef struct var var;

#define CHARTOASCII 0x12345678
#define CONVERTION 1

#if defined(__STDC__) || defined(__cplusplus)
#define CONVERT 1
extern  int * convert_1(var *, CLIENT *);
extern  int * convert_1_svc(var *, struct svc_req *);
extern int chartoascii_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CONVERT 1
extern  int * convert_1();
extern  int * convert_1_svc();
extern int chartoascii_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_var (XDR *, var*);

#else /* K&R C */
extern bool_t xdr_var ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASCII_H_RPCGEN */
