/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ascii.h"

bool_t
xdr_var (XDR *xdrs, var *objp)
{
	register int32_t *buf;

	 if (!xdr_char (xdrs, &objp->chara))
		 return FALSE;
	return TRUE;
}
